name: test

on:
  push: # {branches: [main]}
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    container: ingy/exercism-yamlscript-test-runner:0.1.96

    steps:
    - name: Checkout repository
      uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3

    - name: Touch all
      run: find * -type f | xargs touch

    - name: Run checks and tests
      run: EXERCISM_YAMLSCRIPT_GHA=1 make check
